domain + application логики пользователя
tanyginvv/TL_Recipes pull request #13
Opened 2024-08-14 19:15 UTC by tanyginvv

2024-08-15 18:34 UTC, VladTL commented
Жду полную версию, идея в том, чтобы проект всегда компилировался и работал заявленный функционал. 

Если делить пуллреквесты - то только по фичам(например, фича авторизации и все что с ней связано полностью), а не по слоям.

2024-08-19 19:41 UTC, VladTL requested changes

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Domain/Entities/Recipe.cs
> +    public User User { get; set; }
Author и AuthorId лучше, User непонятно

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +
тут проблемы с форматированием и () лишнее

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/AuthorizationController.cs
> +public class AuthenticationController() : ControllerBase
В названии Authentication, а здесь Authorization. 
Знаешь чем отличается аутентификация от авторизации?

А контроллер лучше все-таки назвать UsersController.

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/AuthorizationController.cs
> +    public async Task<IActionResult> Registrate( [FromBody] RegistrateUserDto registrateUserDto,
register

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Dto/AuthenticationDto/AuthenticationDto.cs
> +    public string PasswordHash { get; init; }
У тебя не соответствует тут название и логика в сервисе. Ты передаешь PasswordHash но в сервисе сравниваешь через метод BCrypt оригинальный пароль и хешированную версию из User, хотя по факту у тебя уже хешированный приходит. Мы с Димой обсудили потом, лучше с фронтенда передавать простой пароль, не хешированный, убери Hash из названия просто, по остальной логике все ок.

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Dto/UserDtos/RegistrateUserDto.cs
> +    public string Description { get; init; }
при регистрации ты не вводишь описание, поэтому поле ненужно.

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Dto/UserDtos/RegistrateUserDto.cs
> +namespace Recipes.WebApi.Dto.UserDto;
namespace некорректный и в других местах тоже.

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/UseCases/Users/Commands/CreateUser/CreateUserCommandHandler.cs
> +namespace Recipes.Application.UseCases.Users.Commands;
namespace

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Dto/UserDtos/RegistrateUserDto.cs
> +    public string Name { get; init; }
Здесь бы тоже валидацию как в других DTO делал, Required там аттрибуты и на длину

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
>      public async Task<ActionResult<RecipeReadIdDto>> CreateRecipe(
видимо не заметил сразу, imageTool здесь точно не должен использоваться, зачем здесь удалять изображение?

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Domain/Entities/User.cs
> +    public string Login { get; set; }
все сеттеры private, для ефки этого хватит. Возможно даже get; init; хватит, но не уверен, проверь)

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/AuthorizationController.cs
> +    public async Task<IActionResult> Authentication( [FromBody] AuthenticationDto authenticationDto,
login будет понятнее, думаю)

Еще укажи конкретный возвращаемый тип а не IActionResult, в соседних местах аналогично.

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/UseCases/Services/AuthService/AuthenticationService.cs
> +        UserAuthorizationToken token = await userAuthorizationTokenRepository.GetByUserIdAsync( user.Id );
А почему AuthorizationToken а не Authentication?) Предлагю просто назвать UserAuthToken чтобы не возникало таких вопросов)

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Domain/Entities/UserAuthorizationToken.cs
> +public class UserAuthorizationToken
UserAuthToken

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Infrastructure/ConfigurationUtils/TokenConfiguration.cs
> +public class TokenConfiguration( IConfiguration configuration ) : ITokenConfiguration
Давай использовать паттерн IOptions

2024-08-19 19:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/UseCases/Services/AuthService/AuthenticationService.cs
> +        DateTime refreshTokenExpiryDate = DateTime.Now.AddDays( tokenConfiguration.GetRefreshTokenValidityInDays() );
UtcNow

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.Application/UseCases/UserAuthorizationTokens/RefreshToken/RefreshTokenCommandHandler.cs
> +        string accessToken = tokenCreator.GenerateAccessToken( token.UserId );
смотри, у тебя этот метод практчиески 1в1 копирует логику из метода AuthenticateUserAsync, различные только входные параметры и способ получения токена. Предлагаю сделать так, чтобы тот сервис принимал на вход UserAuthorizationToken и возвращал TokenDto. И это не команда а тоже должен быть сервис.


Итого, должно получиться:
1. RefreshTokenService - валидирует вход, получает UserAuthorizationToken, вызывает AuthTokenService с userId
2. LoginService , принимает login, password, валидирует, вызывает AuthTokenService  c userId
3. AuthTokenService -> принимает на вход userId  и включает в себя всю логику (подчистка токенов, создание нового токена и т.д.)

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    public async Task<IActionResult> DeleteUser(
это для кого метод?) в дизайне вроде такого функционала не было?

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    public async Task<IActionResult> GetRecipes(
это должно быть в RecipesController, а UserId прокидыватся в спецификацию метода GetRecipes

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +        int id,
напиши явно аттрибуты, [FromRoute], [FromBody]

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Dto/UserDtos/UpdateUserDto.cs
> +    public string OldPasswordHash { get; init; }
не хеш а обычный пароль, у тебя хеша на фронтенде нет и не должно быть

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.Application/UseCases/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +        if ( !string.IsNullOrEmpty( command.OldPasswordHash ) && !string.IsNullOrEmpty( command.NewPasswordHash ) )
а где проверка, что старый пароль - верный?)

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    public async Task<IActionResult> UpdateUser(
Тоже возвращай типы конкретные везде в Task<..>

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    public async Task<ActionResult<UserDto>> GetUserById( int id,
GetUser, без id, просто отдавать текущего юзера

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +public class UsersController() : ControllerBase
объединить контроллер с другим

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    public async Task<ActionResult<ReadUserDto>> GetUserLoginById( int id,
удалить метод, вместе с рецептом отдавать логин автора

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.Application/UseCases/Recipes/Commands/CreateRecipe/CreateRecipeCommand.cs
> +    public required int UserId { get; init; }
что-то не очень секьюрно) это получается можно любой юзерайди прокинуть и ты создашь от другого чувака) нужно отсюда убрать UserId и брать его из JWT Token'a

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        [FromQuery] int userId,
аналогично, нельзя прокидывать userId, надо доставать из Claims

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Dto/RecipeDtos/RecipeUpdateDto.cs
> +    public int UserId { get; set; }
убрать

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        [FromRoute] int userId = 0,
тут тоже можно убрать userId и доставать из claims

2024-08-19 19:41 UTC, VladTL commented on backend/Recipes/Recipes.Application/UseCases/Recipes/Commands/CreateRecipe/CreateRecipeCommandValidator.cs
> +            return Result.FromError( "Количество тегов ограничено до 5 " );
на фронтенде не забудь тоже ограничить)

2024-08-21 19:02 UTC, tanyginvv commented on backend/Recipes/Recipes.Application/UseCases/Users/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +        if ( !string.IsNullOrEmpty( command.OldPasswordHash ) && !string.IsNullOrEmpty( command.NewPasswordHash ) )
В валидаторе

2024-08-22 20:26 UTC, vladisdragon commented
Тоже не сразу заметил, Application/Infrastructure слой принимают IFormFile (зависимость от Microsoft.AspNet) - это неправильно. Нужно прокинуть абстракцию. Можно заюзать паттерн адаптер. Попробуй сделать, если не сможешь - можешь прийти ко мне или к чатужпт)

2024-08-22 20:56 UTC, vladisdragon requested changes

2024-08-22 20:56 UTC, VladDotMe commented on backend/Recipes/Recipes.Infrastructure/ConfigurationUtils/TokenConfiguration.cs
> +public class TokenConfiguration(IOptions<JwtOptions> jwtOptions )  : ITokenConfiguration
пробел

2024-08-22 20:56 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        CreateRecipeCommand command = new()
это через мапстер создавать

2024-08-22 20:56 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        if ( userId is null )
это в аттрибут JwtAuthorization засунуть

2024-08-22 20:56 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        UpdateRecipeCommand command = new() {
тоже автоматически надо маппить

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +public class JwtAuthorizationAttribute : Attribute, IAuthorizationFilter
это не должно быть в Infrastructure, это слой WebApi

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +    private int? GetUserIdFromAccessToken()
это в Extensions, на уровне WebApi

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        JwtSecurityToken token = tokenDecoder.DecodeToken( accessToken );
с токенДекодером будут проблемы, делай его статиком

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        if ( userId is null )
проверка бесполезная, у тебя на уровне аттрибута она уже есть.

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +            context.Result = new ForbidResult();
Unathorized

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +        TokenSignatureVerificator tokenSignatureVerificator = new TokenSignatureVerificator();
тут тоже можно (нужно) получать классы через DI

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +public class JwtAuthorizationAttribute : Attribute, IAuthorizationFilter
Базовое правило - если у тебя в слое Infrastructure/Application/Domain есть какая-либо using  Microsoft.AspNetCore...  что-нибудь там - значит ты делаешь что-то неправильно)

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +            context.Result = new ForbidResult();
UnauthorizedResult

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +            context.Result = new ForbidResult();
UnauthorizedResult

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +            context.Result = new ForbidResult();
UnauthorizedResult

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +        if ( !int.TryParse( userIdClaim.Value, out int userId ) )
объединить с верхней проверкой и параметр discard _

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/JwtAuthorization/JwtAuthorizationAttribute.cs
> +        JwtSecurityToken token = tokenDecoder.DecodeToken( accessToken );
DateTime expDate = DateTimeOffset.FromUnixTimeSeconds( token.Payload.Expiration.Value ).UtcDateTime;

Кстати, уверен, что token всегда != null? Если уверен, пропиши ! везде чтобы не ругался компилятор.  Либо проверь на null

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    private int? GetUserIdFromAccessToken()
удали

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    public async Task<ActionResult<ReadUserDto>> GetUserNameById(
вроде же решили, что не используется и можно удалить?)

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +        if ( userId is null )
проверка лишняя

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +            RecipesCount = user.RecipesCount
RecipeCount правильно. С Count используется единственное число всегда.

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +        if ( userId is null )
тоже проверку убрать

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +        CreateUserCommand createUserCommand = new CreateUserCommand
mapster

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        DeleteRecipeCommand command = new DeleteRecipeCommand
mapster

2024-08-22 20:56 UTC, vladisdragon commented on backend/Recipes/Recipes.Application/UseCases/Recipes/Commands/CreateRecipe/CreateRecipeCommandHandler.cs
> +            imageTools.DeleteImage( createRecipeCommand.ImageUrl );
С этим тоже есть проблема. Ну и в целом есть сейчас проблема с исключениями, которые могут возникнуть на уровне хендлеров при работе с базой, например. Сейчас в таком случае с бекенда выбросится 500я ошибка, что не очень хорошо. 

Варианта вижу два:
1. Middleware на обработку ошибок (скорее всего так все сделают)
2. Предпочительный как по мне - написать общий декоратор на все хендлеры, который: во-первых будет валидировать (т.к. это общая лоигка во всех хендлерах и можно будет убрать ее из самих хенлдеров), во-вторых отлавивать все ошибки try/catch и конвертировать их в Result., в-третьих, делать cleanup при необходимости. Ну и плюс ResultError лучше расширить и добавить кастомнйы тип, чтобы с бекенда возвращать разные статусы а не только BadRequest().  Можно заюзать библиотеку типа Scuptor, можно написать самому, если не получится - приходи.

2024-08-23 19:51 UTC, tanyginvv commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +    public async Task<ActionResult<ReadUserDto>> GetUserNameById(
Переделал метод для получения имени пользователя при авторизации, чтобы отображать в headere на фронте.

2024-08-24 17:00 UTC, vladisdragon requested changes

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/JwtAuthorization/JwtAuthorizationAttribute.cs
> +        }
if ( token?.Payload?.Expiration is null || DateTime.UtcNow > DateTimeOffset.FromUnixTimeSeconds( token.Payload.Expiration.Value ).UtcDateTime )

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
>          [FromRoute, Range( 1, int.MaxValue )] int id,
а зачем? у тебя в дтохе передается же айди

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        DeleteRecipeCommand command = new DeleteRecipeCommand
все еще не мапстер..

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        if ( !HttpContext.Items.TryGetValue( "userId", out object userIdObj ) || userIdObj is not int userId )
убрать все return Unathorized() из методво контроллера, для получения юзерайди юзать Extensions. и использовать вида HttpContext.User.GetUserId();

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
>          GetRecipesQuery query = new GetRecipesQuery
тоже мапстер

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/RecipesController.cs
> +        int userId = HttpContext.GetUserIdFromAccessToken( tokenDecoder ) ?? 0;
tokenDecoder не круто передавать, сделай его статическим просто

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/Tokens/DecodeToken/TokenDecoderAdapter.cs
> +public class TokenDecoderAdapter : ITokenDecoder
зачем?? удалить этот класс, использовать напрямую статический метод в Extensions

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/Tokens/DecodeToken/TokenDecoder.cs
> +public static class TokenDecoder
можно назвать TokenUtils

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/JwtAuthorization/JwtAuthorizationAttribute.cs
> +        try
давай лучше try/catch на весь метод повесим на всякий случай, мало ли чего упасть здесь может..  + логгирование добавить в случае падения ошибки. Используй дефолтный ILogger от майкрософта и прокинь через DI, потом можно будет либу накатить чтобы в файлы писать и т.д., но пока дефолтного хватит, который будет в консоль писать.

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/ImagesController.cs
>          if ( image is null )
есть аттрибут [NotNull]. Но проверь плз, что он выбрасывает ошикбу, потому что я не на 100% уверен

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Adapters/FormFileAdapter.cs
> +    public class FormFileAdapter( IFormFile formFile ) : IFile
классно сделал) только поправь неймспейс

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/ImageTools/ImageHelper.cs
> +        private const string StorageUrl = "../Recipes.Infrastructure/Storage";
а еще, я бы путь законфигурил через appsettings.json и этот файл можно назвать FileImageTools (чтобы явно сказать, что мы сохраняем и достаем изображения из файлов, вдруг потом появится какой-нибудь DatabaseImageTools или CloudImageTools и т.д.)

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/ImageTools/ImageHelper.cs
> +            if ( file is null || file.Length == 0 )
здесь не хватает try/catch тоже на весь метод, может упасть что-нибудь, все таки с I/O работаем, там всегда повышенный риск ошибок.

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.Application/Interfaces/IImageTools.cs
> +    Task<string> SaveImageAsync( IFile image );
а еще так-то в можно тоже в Result все обернуть чтобы не проверять на null а проверять, на IsSuccess, но здесь в целом не так критично

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/Controllers/UsersController.cs
> +        if ( !HttpContext.Items.TryGetValue( "userId", out object userIdObj ) || userIdObj is not int userId )
тут тоже везде не забудь переделать

2024-08-24 17:00 UTC, vladisdragon commented on backend/Recipes/Recipes.WebApi/JwtAuthorization/JwtAuthorizationAttribute.cs
> +    private readonly ITokenDecoder tokenDecoder;
что-то здесь не так, поля не прокидываются

2024-08-24 17:16 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/ConfigurationUtils/JwtOptions.cs
пробежался еще по структуре, папку и неймспейс назови "OptionsS"

2024-08-24 17:22 UTC, vladisdragon commented on backend/Recipes/Recipes.Infrastructure/Entities/Recipes/RecipeConfiguration.cs
А папку Entities лучше назвать DataAccess и в нее же можно рядом положить RecipesDbContext и UnitOfWork

2024-08-24 18:16 UTC, vladisdragon commented
А еще Validator из папки Validators перенеси в CQRSInterfaces, это же тоже к этому относится. Лишние папки плодить не очень хорошо.

2024-08-24 19:12 UTC, vladisdragon commented on backend/Recipes/Recipes.Application/UseCases/Recipes/Commands/CreateRecipe/CreateRecipeCommandHandler.cs
> +            imageTools.DeleteImage( createRecipeCommand.ImageUrl );
UPD: Я тут понял, что с декораторами я немного погорячился, куда лучше/проще сделать абстрактный класс + шаблонный метод.

2024-08-31 13:20 UTC, VladDotMe commented
Щас еще заметил, в Program.cs
string environmentName = Environment.GetEnvironmentVariable( "JSON_CONFIG_NAME" ) ?? "Development";

Здесь fallback на Development, хотя appsettings.Development.json нет, надо добавить. И лучше просто написать ?? "dev"

2024-08-31 14:39 UTC, VladDotMe commented
У BaseRepository добавь неймспейс

2024-08-31 14:43 UTC, VladDotMe commented
IFilter лучше положить в папку Filters

2024-08-31 15:11 UTC, VladDotMe requested changes

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Program.cs
> +string environmentName = Environment.GetEnvironmentVariable( "JSON_CONFIG_NAME" ) ?? "Development";
Здесь fallback на Development, хотя appsettings.Development.json нет, надо добавить. И лучше просто назвать "dev" вместо "Development"

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +            await HandleExceptionAsync( command );
Это не Exception, HandleException должен быть в нижнем catch блоке..

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +            await HandleExceptionAsync( command );
И удалять изображение тебе нужно там же а не в случае валидации, т.к. может произойти какая-либо ошибка сохранения рецепта в базу и тогда тебе тоже нужно удалять изображение.

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/Program.cs
> +        policy.WithOrigins( "http://localhost:3000" )
урл в конфиг

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +            await HandleExceptionAsync( command );
Здесь аналогично предыдущему комменту

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +public abstract class CommandBaseHandler<TCommand, TResult>( IAsyncValidator<TCommand> validator )
еще бы базовые классы вынести отдельно. В идеале 4 файла (все интерфейсы по разным файлам, все классы по разным файлам)

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +    protected abstract Task<Result<TResult>> HandleAsyncImpl( TCommand command );
Async в конец

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Infrastructure/ImageTools/FileToolConfiguration.cs
> +public class FileToolConfiguration( IOptions<FileToolsOptions> toolOptions) : IFileToolConfiguration
лишний класс же, зачем? IOptions сам по себе мокается, если что)

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Infrastructure/ImageTools/FileToolsOptions.cs
> +    public string StorageUrl { get; set; }
Ну и это можно в папку Options перенести рядом со всеми

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/Interfaces/IFileToolConfiguration.cs
> +public interface IFileToolConfiguration
этот удалить

2024-08-31 15:11 UTC, VladDotMe commented on backend/Recipes/Recipes.Infrastructure/ConfigurationUtils/TokenConfiguration.cs
> +public class TokenConfiguration( IConfiguration configuration ) : ITokenConfiguration
После добавления IOptions, класс тоже лишним получается..

2024-08-31 20:45 UTC, tanyginvv commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +    protected abstract Task<Result<TResult>> HandleAsyncImpl( TCommand command );
Студия говорит, что можно использовать async только в методах, которые имеют тело, в командах async прописан

2024-08-31 21:12 UTC, tanyginvv commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +            await HandleExceptionAsync( command );
По сути у меня же сначала отправляется фото и я получаю урл, и если валидация не пройдена, я удаляю картинку, и если что-то пошло не так уже после пройденной валидации также ее удаляю. Таким образом, в двух местах нужно оставить, по-моему.

2024-09-02 07:39 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/CQRSInterfaces/ICommandHandler.cs
> +    protected abstract Task<Result<TResult>> HandleAsyncImpl( TCommand command );
> Студия говорит, что можно использовать async только в методах, которые имеют тело, в командах async прописан

я про название метода

2024-09-02 15:58 UTC, VladDotMe approved these changes

2024-09-02 15:58 UTC, VladDotMe commented on backend/Recipes/Recipes.Infrastructure/ImageTools/FileImageTools.cs
> +public class FileImageTools( IOptions<FileToolsOptions> fileTool ) : IImageTools
fileToolsOptions

2024-09-02 15:58 UTC, VladDotMe commented on backend/Recipes/Recipes.WebApi/appsettings.prod.json
> +        "Secret": "96b14af9-337d-44e0-ae81-f6af75ba9b38",
кстати, на разных средах обычно разные токены. Ну это так, на будущее, пока у тебя тут все равно везде тестовые данные.

2024-09-02 19:04 UTC, merged