Добавлены все тесты
tanyginvv/TL_Recipes pull request #19
Opened 2024-09-14 13:06 UTC by tanyginvv

2024-09-17 10:41 UTC, VladDotMe requested changes

2024-09-17 10:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application/UseCases/Ingredients/Commands/UpdateIngredients/UpdateIngredientsCommandValidator.cs
> +        HashSet<int> stepNumbers = new HashSet<int>();
зач создал и не используешь?

2024-09-17 10:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application.Tests/Recipes.Application.Tests.csproj
> +
лишняя строка

2024-09-17 10:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Domain/Entities/User.cs
> +    public User()
это не круто делать публичные конструкторы или методы для тестов, это получается ты сможешь создать User'a в состоянии в котором он быть не должен (без данных), вместо этого лучше в тестах использовать честный конструктор с произвольным набором данных. Если лень везде в тестах писать new User(...) , можешь на уровне тестов Extensions написать который будет возвращать User и другие доменные сущности с рандомным набором данных.

2024-09-17 10:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application.Tests/Tags/Command/GetOrCreateTag/GetOrCreateTagCommandHandlerTests.cs
> +    public async Task HandleImplAsync_Should_Return_Existing_Tag_When_Tag_Exists()
Именования тестов некорректные. На самом деле есть два варианта, либо так как тут либо Method_Scenario_ExpectedBehaviour, мы сами у себя в команде спорим как лучше) Но главное, чтобы все было в одном стиле. У тебя по большей части написано в стиле
Method_Scenario_ExpectedBehaviour, поэтому пиши так везде)

2024-09-17 10:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application.Tests/Tags/Command/GetOrCreateTag/GetOrCreateTagCommandHandlerTests.cs
> +            .Callback<Tag>( tag => { /* Simulate adding the tag */ } );
ну тут видно, что гпт генерил) бесполезный Callback да и newTag выше не используется.
Гпт в целом норм тема, но за ним надо все перепроверять)

2024-09-17 10:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application.Tests/Tags/Command/UpdateRecipeTags/UpdateRecipeTagsCommandHandlerTests.cs
> +    public async Task HandleAsync_Should_Add_New_Tags_And_Not_Duplicate()
Тут тоже именования не те. Можешь тупо весь класс в гпт выгрузить и попросить переименовать.

2024-09-17 10:41 UTC, VladDotMe commented on backend/Recipes/Recipes.Application.Tests/Favourites/Command/CreateFavourite/CreateFavouriteCommandHandlerTests.cs
> +public class CreateFavouriteCommandHandlerTests
Еще неймспейсы нигде не указал, можешь IDEшкой везде поставить, там есть такая фича.

2024-09-18 18:27 UTC, merged

2026-01-17 19:32 UTC, Qwepce commented on backend/Recipes/Recipes.Application.Tests/Favourites/Command/CreateFavourite/CreateFavouriteCommandHandlerTests.cs
> +        Assert.False( result.IsSuccess );
Вадим, перепиши на флюент плиз