Frontend main page с компонентом поиска
tanyginvv/TL_Recipes pull request #5
Opened 2024-07-26 21:58 UTC by tanyginvv

2024-07-30 05:47 UTC, Nafanyan requested changes
пока просто пробежался, на фронте ты от нас отдохнешь, мы не будем тебя сильно мучать по нему т.к. нам самим надо будет много что узнать)

2024-07-30 05:47 UTC, Nafanyan commented on frontend/Recipes_frontend/src/assets/images/card1.png
назовем иконки как-то более менее говоряще? или дальше возникнут трудности с их использованием?

2024-07-30 05:47 UTC, Nafanyan commented on frontend/Recipes_frontend/src/components/footer/footer.module.css
> +}
пустая строка

2024-07-30 05:47 UTC, Nafanyan commented on frontend/Recipes_frontend/src/components/homePage/homePage.module.css
> +
пустая строка

2024-07-30 05:47 UTC, Nafanyan commented on frontend/Recipes_frontend/src/components/searchComponent/searchComponent.tsx
> +const tagService = new TagService('http://localhost:5218/api/tags');
пока так, дальше 'http://localhost:5218/api/tags' вынесем в конфиг?

2024-07-30 05:47 UTC, Nafanyan commented on frontend/Recipes_frontend/src/models/types.ts
> +
пустая строка

2024-07-31 12:19 UTC, tanyginvv commented on frontend/Recipes_frontend/src/components/searchComponent/searchComponent.tsx
> +const tagService = new TagService('http://localhost:5218/api/tags');
да, дальше уже вынес

2024-08-12 08:37 UTC, VladTL commented
rebase на мастер

2024-09-02 19:05 UTC, closed without merging